### PR TITLE
Optimize e621 command + cooldown

### PR DESCRIPTION
**Pull request by ReperakDev**

### CODE REVIEW

**Comment by Snivine** [comment]
Remove the cooldown and I'll merge it

**Comment by ReperakDev** [comment]
So you want people to be able to spam it?

**Comment by Snivine** [comment]
If I didn't added cooldown in the first place then yes, this is a private bot only like 4 of us should be able to have it

**Comment by Snivine** [comment]
I kinda merged ur changes, thanks bro, IDK how to add you into the commit tho so It'll stay like that XD

**Pull request closed without merging**
